---
# file: playbook-virtualbox.yml

- name: Install requirements.
  hosts: local
  become: true
  tasks:
    - name: Install requirements for vagrant
      ansible.builtin.include_role:
        name: coglinev3.ansible_common
      vars:
        common_packages:
          - bridge-utils
          - libxslt-dev
          - libxml2-dev
          - libvirt-dev
          - zlib1g-dev
          - ruby-dev
    - name: Install Vagrant
      ansible.builtin.include_role:
        name: coglinev3.vagrant
      vars:
        vagrant_packages:
          - vagrant
          - vagrant-hostmanager
    - name: Install Virtualbox
      ansible.builtin.include_role:
        name: coglinev3.virtualbox
