---
vagrant_config:
  env: 'production'
  staging:
    hostmanager_manage_host: true
    hostmanager_include_offline: true
    vbguest_auto_update: true
    dynamic_inventory: true
  production:
    hostmanager_manage_host: false
    hostmanager_include_offline: true
    vbguest_auto_update: false
    dynamic_inventory: true
