---
site_name: Ansible Development Environment
site_description: A development environmwnt for Ansible.
site_author: Cogline.v3

repo_url: https://gitlab.com/cogline_vagrant/ansible-development
edit_uri: https://gitlab.com/cogline_vagrant/ansible-development/tree/master/docs

pages:
  - Home: index.md
  - Motivation: motivation.md
  - Getting Started: getting_started.md
  - Test Ansible Roles: test_ansible_roles.md
  - The Vagrant Environment:
      - The Vagrantfile in Details: vagrant_environment/vagrantfile.md 
  - Download Vagrant Boxes: download_images.md
  - Save, Restore and Delete: save_restore_delete.md
  - License: LICENSE.md

theme:
  name: readthedocs

extra_css:
  - css/extra.css

markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - type: 'gitlab'
      link: 'https://gitlab.com/cogline_vagrant/ansible-development.git'
    - type: 'github'
      link: 'https://github.com/coglinev3/vagrant-ansible-init'
  version: 1.1.1

copyright: Copyright &copy; 2018 Cogline.v3. Release 1.1.1.
