---
site_name: Vagrant Environment for Testing Ansible Roles

site_description: A Multi-VM Vagrant environment for Developing and Testing Ansible Roles.
site_author: Cogline.v3

repo_url: https://github.com/coglinev3/ansible-development
edit_uri: https://github.com/coglinev3/ansible-development/tree/master/docs

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - dosini
    - rust
  analytics:
    gtag: G-S4WJCL5RVX

nav:
  - Multi-VM Vagrant environment: index.md
  - Motivation: motivation.md
  - Quick Start Guide: getting_started.md
  - Developing and Testing Ansible Roles: test_ansible_roles.md
  - Vagrant environment details:
      - Directory structure: environment/directory_structure.md
      - Configuration options: environment/config_options.md
      - Vagrantfile: environment/vagrantfile.md
  - Vagrant provider specific tasks:
      - 'VirtualBox': 'provider/virtualbox.md'
      - 'KVM with QEMU and libvirt': 'provider/libvirt.md'
  - Install and upgrade Vagrant Boxes: download_images.md
  - About:
      - Release Notes: release_notes.md
      - License: LICENSE.md

extra_css:
  - css/extra.css

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - def_list
  - extra
  - fenced_code
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - type: 'github'
      link: 'https://github.com/coglinev3/ansible-development.git'
    - type: 'github'
      link: 'https://github.com/coglinev3/vagrant-ansible-init'
  version: 3.1.0

copyright: Copyright &copy; 2023 Cogline.v3. Release 3.1.0
