---
#site_name: Ansible development with Vagrant and VirtualBox
site_name: Vagrant Environment for Testing Ansible Roles

site_description: A Multi-VM Vagrant environment for Developing and Testing Ansible Roles.
site_author: Cogline.v3

repo_url: https://gitlab.com/cogline_vagrant/ansible-development
edit_uri: https://gitlab.com/cogline_vagrant/ansible-development/tree/master/docs

nav:
  - Multi-VM Vagrant environment: index.md
  - Motivation: motivation.md
  - Getting Started: getting_started.md
  - Developing and Testing Ansible Roles: test_ansible_roles.md
  - Vagrant provider specific tasks: 
      - 'VirtualBox': 'provider/virtualbox.md'
      - 'libvirt (KVM)': 'provider/libvirt.md'
  - The Vagrantfile in Details: vagrantfile.md 
  - Download Vagrant Boxes: download_images.md
  - About:
    - Release Notes: release_notes.md
    - License: LICENSE.md

theme:
  name: readthedocs
  hljs_languages:
    - yaml
    - dosini

extra_css:
  - css/extra.css

markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - type: 'gitlab'
      link: 'https://gitlab.com/cogline_vagrant/ansible-development.git'
    - type: 'github'
      link: 'https://github.com/coglinev3/vagrant-ansible-init'
  version: 1.2.0

copyright: Copyright &copy; 2019 Cogline.v3. Release 1.2.0.
