# Install needed roles from Ansible Galaxy

- src: coglinev3.vagrant_ansible_init
  version: master
  name: coglinev3.vagrant_ansible_init

- src: coglinev3.ansible_python
  version: master
  name: coglinev3.ansible_python

- src: coglinev3.ansible_common
  version: master
  name: coglinev3.ansible_common

# This roles manages OS users and groups.
- src: sansible.users_and_groups
  version: master
  name: sansible.users_and_groups

# Installs a set of dotfiles from a given Git repository.
- src: geerlingguy.dotfiles
  version: master
  name: geerlingguy.dotfiles
