# Install needed roles from the Ansible Galaxy

- src: coglinev3.vagrant-ansible-init
  version: master
  name: coglinev3.vagrant-ansible-init

- src: coglinev3.ansible-common
  version: master
  name: coglinev3.ansible-common

# This roles manages OS users and groups.
- src: sansible.users_and_groups
  version: master
  name: sansible.users_and_groups

# Installs a set of dotfiles from a given Git repository.
#- src: geerlingguy.dotfiles
#  version: master
#  name: geerlingguy.dotfiles
